// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List the practitioner's clients (id, name, email, tier, archived state).",
  inputSchema: {
    include_archived: z.boolean().optional().describe("Include archived clients. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    let q = db(ctx).from("clients").select("id, name, email, tier, client_type, archived_at, created_at").order("created_at", { ascending: false });
    if (!include_archived) q = q.is("archived_at", null);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-client.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_client_default = defineTool2({
  name: "get_client",
  title: "Get client details",
  description: "Fetch a single client's full profile including macros, tier, and phase settings.",
  inputSchema: {
    client_id: z2.string().uuid().describe("The client's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await db2(ctx).from("clients").select("*").eq("id", client_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Client not found or not accessible." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { client: data }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_messages_default = defineTool3({
  name: "list_messages",
  title: "List messages with a client",
  description: "Return the most recent chat messages between the practitioner and a client, oldest first.",
  inputSchema: {
    client_id: z3.string().uuid(),
    limit: z3.number().int().min(1).max(200).optional().describe("Max messages to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await db3(ctx).from("messages").select("id, sender, body, created_at").eq("client_id", client_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ordered = (data ?? []).slice().reverse();
    return {
      content: [{ type: "text", text: JSON.stringify(ordered, null, 2) }],
      structuredContent: { messages: ordered }
    };
  }
});

// src/lib/mcp/tools/send-message.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var send_message_default = defineTool4({
  name: "send_message",
  title: "Send message to client",
  description: "Send a chat message from the signed-in practitioner to one of their clients.",
  inputSchema: {
    client_id: z4.string().uuid(),
    body: z4.string().trim().min(1).describe("Message text to send.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ client_id, body }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await db4(ctx).from("messages").insert({ client_id, sender: "practitioner", body }).select("id, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Sent. id=${data?.id}` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/list-checkins.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
function db5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_checkins_default = defineTool5({
  name: "list_checkins",
  title: "List client check-ins",
  description: "Return recent check-in submissions for a client (weight, notes, submitted_at), newest first.",
  inputSchema: {
    client_id: z5.string().uuid(),
    limit: z5.number().int().min(1).max(100).optional().describe("Max check-ins to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const { data, error } = await db5(ctx).from("checkins").select("*").eq("client_id", client_id).order("submitted_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { checkins: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mzwsjiuwctmlioloqswj";
var mcp_default = defineMcp({
  name: "tenacia-mcp",
  title: "Tenacia MCP",
  version: "0.1.0",
  instructions: "Tools for the Tenacia nutrition-coaching app. Callers act as the signed-in practitioner: list their clients, read a client's profile and check-ins, and send chat messages. All data access is scoped by the app's row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, get_client_default, list_messages_default, send_message_default, list_checkins_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
